fix: make private-package truly optional, Closes #2
Motivation:
terraform fails with the following error when private-package is not set:

    Error: Attempt to get attribute from null value

      on .terraform/modules/control-plane/variables.tf line 169, in variable "private-package":
      169:     condition     = var.private-package == null || length(var.private-package.bucket) > 0

    This value is null, so it does not have any attributes.

The || operator does not short-circuit in Terraform variable validation blocks,
so var.private-package.bucket is evaluated even when var.private-package is null.

Modifications:
 * Replace with ternary expression

Result:
One can define a terraform configuration without configuring private-package

Co-authored-by: jdupas-sudo <jdupas@gatling.io>